# Generated by Django 3.2.9 on 2021-11-06 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xinwen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xinwen',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
