# Generated by Django 3.2.9 on 2021-11-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xinwen', '0002_xinwen_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='xinwen',
            name='img_url',
            field=models.ImageField(default=111, upload_to='img_url/', verbose_name='图片地址'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='xinwen',
            name='biaoti',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='xinwen',
            name='neirong',
            field=models.CharField(max_length=1000, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='xinwen',
            name='zuozhe',
            field=models.CharField(max_length=20, verbose_name='作者'),
        ),
    ]
