# Generated by Django 3.2.9 on 2021-11-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imagefile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagename', models.ImageField(blank=True, null=True, upload_to='')),
                ('labelnote', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imagelabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagename', models.CharField(blank=True, max_length=100, null=True)),
                ('x1', models.CharField(blank=True, max_length=10, null=True)),
                ('y1', models.CharField(blank=True, max_length=10, null=True)),
                ('x2', models.CharField(blank=True, max_length=10, null=True)),
                ('y2', models.CharField(blank=True, max_length=10, null=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('warn', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('pwd', models.CharField(blank=True, max_length=100, null=True)),
                ('authority', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userimgae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('imagename', models.CharField(blank=True, max_length=100, null=True)),
                ('labelnote', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
