# Generated by Django 3.2.9 on 2021-11-21 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_site', '0002_imagelabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
